version: '3.8'

services:
  keystamp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - RUST_LOG=info
      - NOSTR_PRIVATE_KEY=${NOSTR_PRIVATE_KEY}
      - CYPHERNODE_API_URL=http://proxy:8000  # Internal Docker network URL
    networks:
      - cyphernode
    depends_on:
      - proxy

networks:
  cyphernode:
    external: true 