version: '3.8'

services:
  keystamp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - RUST_LOG=info
      - NOSTR_PRIVATE_KEY=${NOSTR_PRIVATE_KEY}
    networks:
      - app_network

networks:
  app_network:
    driver: bridge 