version: '3.8'

services:
  keystamp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - RUST_LOG=info
      - NOSTR_PRIVATE_KEY=${NOSTR_PRIVATE_KEY}
    networks:
      - cyphernode
    depends_on:
      - cyphernode

networks:
  cyphernode:
    external: true 